### ISSUE TITLE
Crash when I click on the welcome page

### ISSUE THREAD

**Issue by XdoctorwhoZ** [Panduza/panduza_sandbox_flutter#17]
it seems that icons are missing (on main)
![image](https://github.com/Panduza/panduza_sandbox_flutter/assets/1451383/3ebab171-a2a4-444e-a577-34f57bc7f56d)

**Comment by XdoctorwhoZ** [comment]
I do not have the problem on android app

**Comment by XdoctorwhoZ** [comment]
Low priority, focus on may deadline

**Comment by Darcraytore1** [comment]
@XdoctorwhoZ Pretty sure it is the same problem Antoine have been with shared preference, you must have data on the disk of previous versions of the app who are not correct anymoren, because I didn't have this problem building debug or release version with windows.

To clean your data on the disk you can put the line "prefs.clear();" in the main file inside of the main method, after initialization of prefs. 
Something like that : 

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  SharedPreferences prefs = await SharedPreferences.getInstance();
  prefs.clear();
  runApp(PanduzaSandboxApp(
    prefs: prefs,
  ));
}

Or you can remove the file of shared preferences on windows is location is : C:\Users\[YourUser]\AppData\Roaming\com.example\panduza_sandbox_flutter\shared_preferences.json

**Comment by XdoctorwhoZ** [comment]
Ok, I let this issue open. There must be a way to manage this error in the code by detecting "old prefs".
