### ISSUE TITLE
Local discovery issues

### ISSUE THREAD

**Issue by wardru** [Panduza/panduza_sandbox_flutter#9]
I have a ton of error messages when I click on local discovery even though I have brokers running locally.
They don't appear.

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Send failed (OS Error: Network is unreachable, errno = 101), address = fd4c:4b32:3232:0:1ac0:4dff:fe66:61e, port = 63500
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1269)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2582)
#2      platformDiscovery (package:panduza_sandbox_flutter/data/utils.dart:194)
<asynchronous suspension>
#3      _DiscoveryPageState.build.<anonymous closure>.<anonymous closure> (package:panduza_sandbox_flutter/after_setup_pages/discovery_page.dart:122)
<asynchronous suspension>
```

**Comment by Darcraytore1** [comment]
I think you didn't understand properly how works the local discovery. In fact we are using the platform to get the current broker (ip + port) used by the platform. So you need to have your platform running and connected to the broker you want to discover to get his information (ip + port). Here, your error message indicates that the message was not correctly transmitted to the platform, most likely because it's not currently running on a machine on your local network. You could retry using the current rust platform on the main branch and having it connected to the broker you want to discover.

**Comment by wardru** [comment]
I know that the platform needs to run, I mentioned brokers running locally instead of platforms, my bad.
I tested with the Python platform, maybe it doesn't support local discovery?

Nonetheless, it's not a valid way to handle it. An unhandled Exception is always a bug, always.
You must always catch what can be thrown, and be in control of your error handling.

Just nicely catch all  the connections that didn't succeed. If no platform has been found, print a nice message to your user, to let him know it failed and that a platform must be running and the local network.

PS: please let the person that created the issue close it, it's easier to track

**Comment by XdoctorwhoZ** [comment]
@Darcraytore1 I think the problem @wardru have is because the issue you have opened to explain that the port should be appended in the LSD response payload.

**Comment by Darcraytore1** [comment]
Yep exactly we need to change LSD to give the correct port

**Comment by Darcraytore1** [comment]
It's suppose to be fix with may version of the app

**Comment by wardru** [comment]
Awesome, it's way cleaner thanks!
